### ISSUE TITLE
route가 왜 안될까 ? ^^..

### ISSUE THREAD

**Issue by root-zero-o** [kevinkim910408/ReactGameHeaven#9]
pages/signIn에서 route가 안됩니다 ! 왜 안될까요 !
도와줘 ~~ 준호에몽 ~~~~~~~~~~~~

**Comment by kevinkim910408** [comment]
누가 이거 빼먹음 ^_^ 
    e.preventDefault();


const onClick = (e: React.FormEvent<HTMLFormElement>) => {
    e.preventDefault();
    localStorage.setItem("nickname", nickname);
    route("/gameList");
  };

**Comment by root-zero-o** [comment]
> 누가 이거 빼먹음 ^_^ e.preventDefault();
> 
> const onClick = (e: React.FormEvent) => { e.preventDefault(); localStorage.setItem("nickname", nickname); route("/gameList"); };

제가했는데요
